#spring:
#  rabbitmq:
#    host: 192.168.0.200
#  datasource:
##      url: jdbc:postgresql://10.131.21.234:5432/tpfdb
#        url: jdbc:postgresql://10.1.66.30:5435/ficodb
#security:
#  oauth2:
#    client:
#      access-token-uri: http://192.168.0.200:1100/oauth/token
#    resource:
#      token-info-uri: http://192.168.0.200:1100/oauth/check_token
#eureka:
#  client:
#    serviceUrl:
#      defaultZone:  http://192.168.0.200:8761/eureka