spring:
  rabbitmq:
    host: 192.168.0.200
  data:
    mongodb:
      uri: mongodb://192.168.0.200:27017/tpfdb
  url:
    first-check-risk: http://10.131.21.137:52233/sale_page/api_management/firstcheck/
security:
  oauth2:
    client:
      access-token-uri: http://192.168.0.200:1100/oauth/token
    resource:
      token-info-uri: http://192.168.0.200:1100/oauth/check_token
eureka:
  client:
    serviceUrl:
      defaultZone:  http://192.168.0.200:8761/eureka