spring:
  rabbitmq:
    host: 10.131.23.30
  data:
    mongodb:
#      uri: mongodb://10.131.21.234:27017/tpfdb
        uri: mongodb://10.131.23.30:27017/tpfdb
  url:
    uploadfile: "123"
security:
  oauth2:
    client:
      access-token-uri: http://10.131.23.30:1100/oauth/token
    resource:
      token-info-uri: http://10.131.23.30:1100/oauth/check_token
eureka:
  client:
    serviceUrl:
      defaultZone:  http://10.131.23.30:8761/eureka