#spring:
#  rabbitmq:
#    host: 10.1.69.14
#  datasource:
##      url: jdbc:postgresql://10.131.21.234:5432/tpfdb
#        url: jdbc:postgresql://10.1.66.30:5435/ficodb
#  redis:
#    host: 10.1.69.14
#    port: 6379
#    timeout: 10000
#  esb:
#    url: https://tpfesbuat.tpb.vn/esb/app/inhouse/ihAutoAllocation/updateAppVendor
#security:
#  oauth2:
#    client:
#      access-token-uri: http://10.1.69.14:1100/oauth/token
#    resource:
#      token-info-uri: http://10.1.69.14:1100/oauth/check_token
#eureka:
#  client:
#    serviceUrl:
#      defaultZone:  http://10.1.69.14:8761/eureka
#  instance:
#    hostname: 10.131.21.130
