spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/FPT_Fico
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    
eureka:
  client:
    serviceUrl:
      defaultZone:  http://192.168.0.203:8761/eureka