version: "3"

networks:
  service_network:
    driver: overlay

services:
  tpf-opensource-git:
    image: gitlab/gitlab-ce:latest
    hostname: tpf-opensource-git
    volumes:
      - ./mount/git:/var/opt/gitlab
    deploy:
      replicas: 1
    networks:
      - service_network
    ports:
      - 8088:80
      - 4443:443
      - 22222:22
