version: "3"

networks:
  service_network:
    driver: overlay

services:
  tpf-opensource-rabbitmq:
    image: rabbitmq:3-management
    hostname: tpf-opensource-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./mount/rabbitmq:/var/lib/rabbitmq/mnesia
    deploy:
      replicas: 1
    networks:
      - service_network
    ports:
      - 15672:15672
      - 5672:5672
