version: "3"

networks:
  service_network:
    driver: overlay

services:
  tpf-service-finnone:
    image: openjdk:11
    hostname: tpf-service-finnone
    working_dir: /opt/tpf-service-finnone
    command: bash -c 'cd /opt/tpf-service-finnone && java -jar tpf-service-finnone-1.0.jar'
    volumes:
      - ./../tpf-service-finnone/target:/opt/tpf-service-finnone
    environment:
      SPRING_PROFILES_ACTIVE: dev
    deploy:
      replicas: 1
    networks:
      - service_network
    ports:
      - 4004:4004
