version: "3"

networks:
  service_network:
    driver: overlay

services:
  tpf-service-app:
    image: openjdk:11
    hostname: tpf-service-app
    working_dir: /opt/tpf-service-app
    command: bash -c 'cd /opt/tpf-service-app && java -jar tpf-service-app-1.0.jar'
    volumes:
      - ./../tpf-service-app/target:/opt/tpf-service-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
    deploy:
      replicas: 1
    networks:
      - service_network
    ports:
      - 4001:4001
