version: "3"

networks:
  service_network:
    driver: overlay

services:
  tpf-service-momo:
    image: openjdk:11
    hostname: tpf-service-momo
    working_dir: /opt/tpf-service-momo
    command: bash -c 'cd /opt/tpf-service-momo && java -jar tpf-service-momo-1.0.jar'
    volumes:
      - ./../tpf-service-momo/target:/opt/tpf-service-momo
    environment:
      SPRING_PROFILES_ACTIVE: dev
    deploy:
      replicas: 1
    networks:
      - service_network
    ports:
      - 4008:4008
