version: "3"

networks:
  service_network:
    driver: overlay

services:
  tpf-service-restclient:
    image: openjdk:11
    hostname: tpf-service-restclient
    working_dir: /opt/tpf-service-restclient
    command: bash -c 'cd /opt/tpf-service-restclient && java -jar tpf-service-restclient-1.0.jar'
    volumes:
      - ./../tpf-service-restclient/target:/opt/tpf-service-restclient
    environment:
      SPRING_PROFILES_ACTIVE: dev
    deploy:
      replicas: 1
    networks:
      - service_network
    ports:
      - 4000:4000
