spring:
  rabbitmq:
    host: 10.131.31.202
  datasource:
    url: jdbc:oracle:thin:@//10.131.21.47:1521/ORCLCDB.localdomain
    username: dummy
    password: dummy
    schema-username: DUMMY
#   driver-class-name: oracle.jdbc.OracleDriver
#    jdbc-url: jdbc:oracle:thin:@10.1.66.32:1521:FICOCEN
#    username: MIS
#    password: Luanpv1#mis#2020
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
  syncfunc:
    fixedRate: "300000"

  syncrobot:
    fixedRate: "300000"

security:
  oauth2:
    client:
      access-token-uri: http://10.131.31.202:1100/oauth/token
    resource:
      token-info-uri: http://10.131.31.202:1100/oauth/check_token
eureka:
  client:
    serviceUrl:
      defaultZone:  http://10.131.31.202:8761/eureka
  instance:
    hostname: 10.131.21.159