spring:
  rabbitmq:
    host: 10.131.31.202
  datasource:
    url: jdbc:oracle://10.1.66.32:1521/FICOCEN
    username: MIS
    password: Luanpv1#mis#2020
security:
  oauth2:
    client:
      access-token-uri: http://10.131.31.202:1100/oauth/token
    resource:
      token-info-uri: http://10.131.31.202:1100/oauth/check_token
eureka:
  client:
    serviceUrl:
      defaultZone:  http://10.131.31.202:8761/eureka
  instance:
    hostname: 10.131.21.130
