spring:
  rabbitmq:
    host: 10.131.23.30
security:
  oauth2:
    client:
      client-id: tpf-service-root
      client-secret: tpf-service-root
    resource:
      token-info-uri: http://10.131.23.30:1100/oauth/check_token
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.131.23.30:8761/eureka
  instance:
    hostname: 10.131.21.57
