#spring:
#  rabbitmq:
#    host: 192.168.0.205
#security:
#  oauth2:
#    resource:
#      token-info-uri: http://192.168.0.205:1100/oauth/check_token
#eureka:
#  client:
#    serviceUrl:
#      defaultZone:  http://192.168.0.205:8761/eureka

