spring:
  rabbitmq:
    host: localhost
security:
  oauth2:
    client:
      client-id: tpf-service-root
      client-secret: tpf-service-root
      access-token-uri: http://10.131.23.30:1100/oauth/token
    resource:
      token-info-uri: http://10.131.23.30:1100/oauth/check_token

eureka:
 client:
   serviceUrl:
     defaultZone:  http://10.131.23.30:8761/eureka