server:
  port: 5000
spring:
  cloud:
    config:
      allow-override: true
      override-none: true
  rabbitmq:
    host: 10.1.66.27
    port: 5672
    username: tpf-service-automation-test
    password: tpf-service-automation-test
    app-id: tpf-service-automation-test
    logstash: tpf-service-logstash-automation
  data:
    mongodb:
      uri: mongodb://10.1.66.27:27017/tpfdb
  url:
    finone: http://10.1.66.85:3333/neutrino-sso-web/login?param=
    seleHost: 127.0.0.1
    selePort: 4444
    downloadFile: http://10.1.66.27:3001/v1/file/
    rabbitIdRes: tpf-service-dataentry
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.1.66.27:8761/eureka
  instance:
    hostname: 127.0.0.1
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN