spring:
  rabbitmq:
    host: localhost
  data:
    mongodb:
      uri: mongodb://10.131.23.30:27017/tpfdb
  url:
    downloadFile: abc
eureka:
  client:
    serviceUrl:
      defaultZone:  http://10.131.23.30:8761/eureka