#spring:
#  rabbitmq:
##    host: localhost
#      host: 10.131.23.30
#      port: 5672
#      username: tpf-service-automation
#      password: tpf-service-automation
#      app-id: tpf-service-automation
#      logstash: tpf-service-logstash-automation
#  data:
#    mongodb:
#      uri: mongodb://10.131.23.30:27017/tpfdb
#  url:
#    finone: http://10.1.66.20:4141/finnone-webapp/app/auth/login
#    seleHost: localhost
#    selePort: 4444
#    downloadFile: http://10.131.23.30:3001/v1/file/
#eureka:
#  client:
#    serviceUrl:
#      defaultZone:  http://10.131.23.30:8761/eureka