#spring:
#  rabbitmq:
#    host: 10.131.31.202
#  data:
#    mongodb:
#      uri: mongodb://10.131.31.202:27017/tpfdb
#eureka:
#  client:
#    serviceUrl:
#      defaultZone:  http://192.168.0.203:8761/eureka